### PR TITLE
mock data

### PR DESCRIPTION
**Pull request by doolumes**

### CODE REVIEW

**Comment by doolumes** [comment]
PR review :DDDDDD

**Comment by carteruh** [comment]
@dionolumese Do we need to add an availability field for the volunteers? @kelseymwong we can probably make a follow-up PR for mock data on event history

**Comment by doolumes** [comment]
@carteruh In practice, volunteers will list their availability on their calendar. Each field in the dictionary is apart of the requirements on the canvas assignment.

**Comment by doolumes** [comment]
image

**Pull request merged**
